In [17]:
import sys

In [18]:
from importlib import reload

In [2]:
sys.path.append(os.path.join(os.path.abspath(os.path.join('../..')), 'src'))

In [3]:
import numpy
import scipy
from scipy import sparse

In [24]:
import graph_utils
from graph_utils import modularity, bNG

In [5]:
kar = graph_utils.loadZachData()

In [26]:
A = kar.copy()

In [19]:
import kernighan_lin

In [158]:
reload(kernighan_lin)

<module 'kernighan_lin' from '/home/immersinn/gits/rssfeed_link_collector/src/kernighan_lin.py'>

In [68]:
core_nodes = [8]
start_nodes = []

In [86]:
indx_orig = numpy.array(range(A.shape[0]))

In [87]:
Bin='bNG'
L = 1.0
verbose=True
indx = indx_orig[:]

# Prep work
if Bin == 'bNG':
    B = lambda v, A, indx: bNG(v, A, indx, L)
elif Bin == 'bRandUni':
    B = lambda v, A, indx: bRandUni(v, A, indx, L)

n = A.shape[0]
k = numpy.array(A.sum(axis=1))
kk2m = ((k * k) / k.sum() * L).reshape((n,))


# Construct initial group
group = numpy.zeros((n,))
for i in core_nodes:
    group[i] = 1
for i in start_nodes:
    group[i] = 1

score = modularity(group, B, A)
if verbose:
    print('Initial score: %s' % score)
indx_orig = indx[:]
score_prev = -999
num_iter = 0

Initial score: -0.324675324675


### Single Iteration

In [88]:
score_prev = score
num_iter += 1
indx = list(indx_orig[:])
group_names = numpy.unique(group[indx])
for k in core_nodes:
    indx.remove(k)  # remove core from consideration

if verbose:
    print('At iteration %s: ' % num_iter)node_contrib = numpy.zeros((n, 2))
for i, c in enumerate(group_names):
    x = (test_group == c).astype(int).reshape((1,n)) 
    node_contrib[:,i] = B(x.T, A, numpy.array(range(n))).reshape((n,))
test_group = group.copy()

At iteration 1: 


#### Iterate until index is gone...

In [148]:
node_contrib = numpy.zeros((n, 2))
for i, c in enumerate(group_names):
    x = (test_group == c).astype(int).reshape((1,n)) 
    node_contrib[:,i] = B(x.T, A, numpy.array(range(n))).reshape((n,))
    
node_contrib

array([[ 4.16233766, -4.16233766],
       [ 2.0974026 , -2.0974026 ],
       [ 1.44155844, -1.44155844],
       [ 2.06493506, -2.06493506],
       [ 1.03246753, -1.03246753],
       [ 1.37662338, -1.37662338],
       [ 1.37662338, -1.37662338],
       [ 1.37662338, -1.37662338],
       [-1.27922078,  1.27922078],
       [-0.31168831,  0.31168831],
       [ 1.03246753, -1.03246753],
       [ 0.34415584, -0.34415584],
       [ 0.68831169, -0.68831169],
       [ 0.72077922, -0.72077922],
       [-1.31168831,  1.31168831],
       [-1.31168831,  1.31168831],
       [ 0.68831169, -0.68831169],
       [ 0.68831169, -0.68831169],
       [-1.31168831,  1.31168831],
       [ 0.03246753, -0.03246753],
       [-1.31168831,  1.31168831],
       [ 0.68831169, -0.68831169],
       [-1.31168831,  1.31168831],
       [-1.27922078,  1.27922078],
       [ 1.03246753, -1.03246753],
       [ 1.03246753, -1.03246753],
       [-1.31168831,  1.31168831],
       [ 0.37662338, -0.37662338],
       [ 0.03246753,

In [149]:
# THIS NEEDS TO BE MODIFIED DOWN THE ROAD
node_contrib = node_contrib.reshape((node_contrib.size,))            

curr_contrib_index = (numpy.array(range(n)) * len(group_names) + test_group).astype(int)
curr_contrib = node_contrib[curr_contrib_index] + kk2m

curr_contrib_index

array([ 0,  2,  4,  6,  8, 10, 12, 14, 17, 18, 20, 22, 24, 26, 29, 31, 32,
       34, 37, 38, 41, 42, 45, 46, 48, 50, 53, 54, 56, 59, 61, 62, 65, 67])

In [150]:
node_contrib = node_contrib -\
               numpy.repeat(curr_contrib, len(group_names))
node_contrib[curr_contrib_index] = -999
node_contrib = node_contrib.reshape((n, 2))

node_contrib = node_contrib[indx,]
curr_contrib = curr_contrib[indx,]

max_contrib = node_contrib.max()

print(node_contrib.shape)
node_contrib

(23, 2)


array([[ -9.99000000e+02,  -9.78571429e+00],
       [ -9.99000000e+02,  -4.72077922e+00],
       [ -9.99000000e+02,  -3.53246753e+00],
       [ -9.99000000e+02,  -4.36363636e+00],
       [ -9.99000000e+02,  -2.12337662e+00],
       [ -9.99000000e+02,  -2.85714286e+00],
       [ -9.99000000e+02,  -2.85714286e+00],
       [ -9.99000000e+02,  -2.85714286e+00],
       [ -9.99000000e+02,   5.97402597e-01],
       [ -9.99000000e+02,  -2.12337662e+00],
       [ -9.99000000e+02,  -6.94805195e-01],
       [ -9.99000000e+02,  -1.40259740e+00],
       [ -9.99000000e+02,  -1.60389610e+00],
       [ -9.99000000e+02,  -1.40259740e+00],
       [ -9.99000000e+02,  -1.40259740e+00],
       [ -9.99000000e+02,  -1.23376623e-01],
       [ -9.99000000e+02,  -1.40259740e+00],
       [ -9.99000000e+02,   2.39610390e+00],
       [ -9.99000000e+02,  -2.12337662e+00],
       [ -9.99000000e+02,  -2.12337662e+00],
       [ -9.99000000e+02,  -8.57142857e-01],
       [ -9.99000000e+02,  -1.23376623e-01],
       [ -

In [151]:
# Get best move, rando break ties
(inds, grps) = numpy.where(node_contrib == max_contrib)
rand_tie_break = numpy.random.randint(0, len(inds))
best_node = indx[inds[rand_tie_break]]
best_group = grps[rand_tie_break]

best_node, best_group

(23, 1)

In [152]:
# Update node-group assignment
test_group[best_node] = best_group
indx.remove(best_node)
new_score = modularity(test_group, B, A, indx_orig)

new_score

46.311688311688314

In [153]:
test_group

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,
        1.,  0.,  0.,  1.,  1.,  0.,  1.,  1.])

In [175]:
kernighan_lin.mKLLocal([1], A, index_orig, L=4, verbose=True, start_nodes=[0,3])

Initial score: 143.246753247
At iteration 1: 
New groups after iteration 1: [1 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0 0 0]
At iteration 2: 
New groups after iteration 2: [1 1 0 1 1 1 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
At iteration 3: 
New groups after iteration 3: [1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
At iteration 4: 
New groups after iteration 4: [1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 1 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]


(array([0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), 270.98701298701297)

In [176]:
kernighan_lin.mKLLocal([6], A, index_orig, L=4, verbose=True, start_nodes=[4,5,10])

Initial score: 89.8181818182
At iteration 1: 
New groups after iteration 1: [0 0 0 0 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
At iteration 2: 
New groups after iteration 2: [1 1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0]
At iteration 3: 
New groups after iteration 3: [1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 0]
At iteration 4: 
New groups after iteration 4: [0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1]
At iteration 5: 
New groups after iteration 5: [0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 0 1]


(array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1]), 259.7012987012987)